Nop.Plugin.Payments.Rave/Controllers/PaymentRaveController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Plugin.Payments.Rave.Models;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Orders;
using Nop.Services.Payments;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Services.Messages;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Nop.Core.Domain.Payments;
using System;
using System.Text;
using Nop.Services.Directory;
using Nop.Core.Domain.Directory;
using System.Security.Cryptography;

namespace Nop.Plugin.Payments.Rave.Controllers
{
    public class PaymentRaveController : BasePaymentController
    {

        #region Fields
        private readonly INotificationService _notificationService;
        private readonly IWorkContext _workContext;
        private readonly ISettingService _settingService;
        private readonly IPaymentService _paymentService;
        private readonly IOrderService _orderService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IPermissionService _permissionService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ILocalizationService _localizationService;
        private readonly IStoreContext _storeContext;
        private readonly ILogger _logger;
        private readonly IWebHelper _webHelper;
        private readonly ShoppingCartSettings _shoppingCartSettings;
        private readonly RavePaymentSettings _RavePaymentSettings;
        private readonly ICurrencyService _currencyService;
        private readonly CurrencySettings _currencySettings;

        #endregion

        #region Ctor

        public PaymentRaveController(
            INotificationService notificationService,
            IWorkContext workContext,
            ISettingService settingService,
            IPaymentService paymentService,
            IOrderService orderService,
            IOrderProcessingService orderProcessingService,
            IPermissionService permissionService,
            IGenericAttributeService genericAttributeService,
            ILocalizationService localizationService,
            IStoreContext storeContext,
            ILogger logger,
            IWebHelper webHelper,
            ShoppingCartSettings shoppingCartSettings,
            RavePaymentSettings ravePaymentSettings,
            ICurrencyService currencyService,
            CurrencySettings currencySettings)

        {
            this._notificationService = notificationService;
            this._workContext = workContext;
            this._settingService = settingService;
            this._paymentService = paymentService;
            this._orderService = orderService;
            this._orderProcessingService = orderProcessingService;
            this._permissionService = permissionService;
            this._genericAttributeService = genericAttributeService;
            this._localizationService = localizationService;
            this._storeContext = storeContext;
            this._logger = logger;
            this._webHelper = webHelper;
            this._shoppingCartSettings = shoppingCartSettings;
            this._RavePaymentSettings = ravePaymentSettings;
            this._currencyService = currencyService;
            this._currencySettings = currencySettings;
        }

        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var ravePaymentSettings = _settingService.LoadSetting<RavePaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                Live = ravePaymentSettings.Live,
                SecretKey = ravePaymentSettings.SecretKey,
                PublicKey = ravePaymentSettings.PublicKey,
                EncryptKey = ravePaymentSettings.EncryptKey

            };
            if (storeScope > 0)
            {
                model.Live_OverrideForStore = _settingService.SettingExists(ravePaymentSettings, x => x.Live, storeScope);
                model.SecretKey_OverrideForStore = _settingService.SettingExists(ravePaymentSettings, x => x.SecretKey, storeScope);
                model.PublicKey_OverrideForStore = _settingService.SettingExists(ravePaymentSettings, x => x.PublicKey, storeScope);
                model.EncryptKey_OverrideForStore = _settingService.SettingExists(ravePaymentSettings, x => x.EncryptKey, storeScope);
                }

            return View("~/Plugins/Payments.Rave/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [AdminAntiForgery]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var ravePaymentSettings = _settingService.LoadSetting<RavePaymentSettings>(storeScope);

            //save settings
            ravePaymentSettings.Live = model.Live;
            ravePaymentSettings.PublicKey = model.PublicKey;
            ravePaymentSettings.SecretKey = model.SecretKey;
            ravePaymentSettings.EncryptKey = model.EncryptKey;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            _settingService.SaveSettingOverridablePerStore(ravePaymentSettings, x => x.Live, model.Live_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(ravePaymentSettings, x => x.PublicKey, model.PublicKey_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(ravePaymentSettings, x => x.SecretKey, model.SecretKey_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(ravePaymentSettings, x => x.EncryptKey, model.EncryptKey_OverrideForStore, storeScope, false);

            //now clear settings cache
            _settingService.ClearCache();

           _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        //action displaying notification (warning) to a store owner about inaccurate Rave rounding
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult RoundingWarning(bool passProductNamesAndTotals)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //prices and total aren't rounded, so display warning
            if (passProductNamesAndTotals && !_shoppingCartSettings.RoundPricesDuringCalculation)
                return Json(new { Result = _localizationService.GetResource("Plugins.Payments.Rave.RoundingWarning") });

            return Json(new { Result = string.Empty });
        }
        public IActionResult CancelOrder()
        {
            var order = _orderService.SearchOrders(storeId: _storeContext.CurrentStore.Id,
                customerId: _workContext.CurrentCustomer.Id, pageSize: 1).FirstOrDefault();
            if (order != null)
                return RedirectToRoute("OrderDetails", new { orderId = order.Id });

            return RedirectToRoute("HomePage");
        }

        //Use this form for redirection after payment.
        //[Authorize]
        //[AutoValidateAntiforgeryToken]
        public ActionResult ReturnPaymentInfo(IFormCollection form)
        {
            var processor = _paymentService.LoadPaymentMethodBySystemName("Payments.Rave") as RavePaymentProcessor;
            if (processor == null || !_paymentService.IsPaymentMethodActive(processor) || !processor.PluginDescriptor.Installed)
            {
                throw new NopException("Rave module cannot be loaded");
            }
            string tranx_id = form["Rave_tranx_id"];
            string tranx_status_code = form["Rave_tranx_status_code"];
            string tranx_status_msg = form["Rave_tranx_status_msg"];
            string Rave_tranx_amt = form["Rave_tranx_amt"];
            string Rave_tranx_curr = form["Rave_tranx_curr"];
            string Rave_cust_id = form["Rave_cust_id"];
            string Rave_gway_name = form["Rave_gway_name"];
            string Rave_echo_data = form["Rave_echo_data"];


            _logger.Information("transid: " + tranx_id);
            _logger.Information("tranx_status_code: " + tranx_status_code);
            _logger.Information("tranx_status_msg: " + tranx_status_msg);
            _logger.Information("Rave_echo_data: " + Rave_echo_data);
            _logger.Information("Rave_tranx_amt: " + Rave_tranx_amt);
            _logger.Information("Rave_tranx_curr: " + Rave_tranx_curr);

            var orderGuid = Guid.Parse(Rave_echo_data);
            Order order = _orderService.GetOrderByGuid(orderGuid);


Nop.Plugin.Payments.Rave/Views/Configure.cshtml
@model Nop.Plugin.Payments.Rave.Models.ConfigurationModel
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_ConfigurePlugin";
}
@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentRave" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Live_OverrideForStore" asp-input="Live" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Live" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Live" />
                        <span asp-validation-for="Live"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SecretKey_OverrideForStore" asp-input="SecretKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SecretKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SecretKey" />
                        <span asp-validation-for="SecretKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PublicKey_OverrideForStore" asp-input="PublicKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PublicKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PublicKey" />
                        <span asp-validation-for="PublicKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EncryptKey_OverrideForStore" asp-input="EncryptKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EncryptKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="EncryptKey" />
                        <span asp-validation-for="EncryptKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Payments.Rave/Views/PaymentInfo.cshtml
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "";
}
<div class="row">
    <div class="col-md-2">
        <img src="@Url.Content($"{webHelper.GetStoreLocation()}Plugins/Payments.Rave/logo.jpg")" alt="Rave" />
    </div>
    <div class="col-md-8">
        <b>@T("Plugins.Payments.Rave.Fields.RedirectionTip")</b>
    </div>
</div>

Nop.Plugin.Payments.Rave/Views/ReturnPaymentInfo.cshtml
@model Nop.Plugin.Payments.Rave.Models.ReturnPaymentInfoModel
@{
    Layout = "_ColumnsOne";

    //title
    Html.AddTitleParts("Payment Information");
    //page class
    Html.AppendPageCssClassParts("html-checkout-page");
    Html.AppendPageCssClassParts("html-order-completed-page");
}

<div class="page checkout-page order-completed-page">   
    <div class="page-title">
        <h1>Rave Payment Declined</h1>
    </div>
    <div class="page-body checkout-data">      
        <div class="section order-completed">
            <div class="title">
                <strong>Payment is declined</strong>
            </div>
            <div class="details">
                <div class="order-number">
                    <strong>Order Number: @Html.Raw(Model.OrderId.ToString())</strong>
                </div>
                <div class="order-number">
                    <strong>Description:  @Html.Raw(Model.DescriptionText)</strong>
                </div>
                <div class="order-number">
                    <strong>Status Code: @Html.Raw(Model.StatusCode)</strong>
                </div>
                <div class="order-number">
                    <strong>Message: @Html.Raw(Model.StatusMessage)</strong>
                </div>
                <div class="details-link">
                    <a href="@Url.RouteUrl("OrderDetails", new { orderID = Model.OrderId })">@T("Checkout.PlacedOrderDetails")</a>
                </div>
            </div>
            <div class="buttons">
                <input type="button" value="@T("Checkout.ThankYou.Continue")" class="button-1 order-completed-continue-button" onclick="setLocation('@Url.RouteUrl("HomePage")')" />
            </div>
        </div>
    </div>
</div>